---
title: "Untitled"
output: pdf_document
date: "2025-02-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library('quantmod')
library(tidyverse)
library(lubridate)
library(xts)
```

```{r}
# Data 
data = read.csv("Shanghai AQI and Wheather 2014-2021.csv")
aqi_levels <- c(
  "Hazardous" = 5,
  "Very unhealthy" = 4,
  "Unhealthy" = 3,
  "Unhealthy for sensitive groups" = 2,
  "Moderate" = 1
)

data = data |>
  mutate(AQI_Numeric = aqi_levels[AQI_Explained]) |>
  mutate(temp = (maxtempC + mintempC)/2, .after = mintempC) |>
  filter(date >= "2017-01-01" & date < "2021-01-01" )

# Keep from 2017-01-01 to 2020-12-31

dates = data$date

data <- data |> 
  select(-c("date"))
  
AQI_data <- xts(data, order.by = as.POSIXct(dates))
#AQI_data is the cleaned dataset we'll use
```

```{r}
# plots ("data1")
data1 <- read.csv("Shanghai AQI and Wheather 2014-2021.csv") |> 
  filter(date >= "2017-01-01" & date < "2021-01-01")

data1$date <- as.POSIXct(data1$date, format="%Y-%m-%d")
data1$AQI <- as.numeric(data1$AQI)
AQI_xts <- xts(data1$AQI, order.by = data1$date)
plot(AQI_xts, main="Shanghai AQI (2017-2020)", lwd=2, ylab="AQI", xlab="Year")

AQI_df <- data.frame(date = index(AQI_data), AQI_data)
aqi_levels <- c(
  "Moderate" = 1,
  "Unhealthy for Sensitive Groups" = 2,
  "Unhealthy" = 3,
  "Very Unhealthy" = 4,
  "Hazardous" = 5
)

AQI_df$AQI_Level <- factor(AQI_df$AQI_Numeric, 
                           levels = c(1, 2, 3, 4, 5), 
                           labels = names(aqi_levels))

aqi_freq <- AQI_df %>%
  count(AQI_Level) %>%
  arrange(desc(n)) 

ggplot(aqi_freq, aes(x = reorder(AQI_Level, -n), y = n, fill = AQI_Level)) +
  geom_bar(stat = "identity") +
  labs(title = "Pollution Levels (AQI ranges)",
       x = "Pollution Level", 
       y = "Frequency") +
  theme_minimal() +
  theme(legend.position = "none")
```


```{r}
#View(AQI_data)

#AQI_data is the cleaned dataset we'll use
```

